### ISSUE TITLE
pub serve does not show Router's superiority

### ISSUE THREAD

**Issue by koorgoo** [angular-examples/toh-5#2] opened 2016-11-24 10:25 UTC
Router supports routes rendering when user opens a new tab with route's URL. Not only when she navigates to it via link in a running application.

Pub serve does not allow to open `http://localhost:8080/dashboard` in a new tab. The error will be: 
```
404 Not Found
Could not find asset web/dashboard in package angular_tour_of_heroes
```

May be it makes sense to store in repo another server code that will provide newbies like me with Router's stunning effect?

Example, `serve.go`:

```
package main

import (
	"io/ioutil"
	"net/http"
	"path"
	"regexp"
)

var (
	root   = "build/web"
	fileRe = regexp.MustCompile(".(html|js|css)$")
)

func main() {
	http.HandleFunc("/", Serve)
	http.ListenAndServe("localhost:8080", nil)
}

func Serve(w http.ResponseWriter, r *http.Request) {
	if fileRe.MatchString(r.URL.Path) {
		serve(w, r.URL.Path)
		return
	}
	serve(w, "index.html")
}

func serve(w http.ResponseWriter, filename string) {
	b, err := ioutil.ReadFile(path.Join(root, filename))
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	contentType := http.DetectContentType(b)
	w.Header().Set("Content-Type", contentType)
	w.Write(b)
}
```

P.S. I am not good at server development with Dart yet. Because of this I placed code in my current favourite language.

**Comment by koorgoo** [comment] 2016-11-24 10:28
Also there must be a section in README.md telling how to run an alternative server:

```bash
$ pub build
$ go run serve.go
```

**Comment by chalin** [comment] 2016-11-29 18:06
Hi. You are correct that there are a few ways to solve this. The problem is not specific to toh-5 so I'll be closing this issue but you can track progress on a general solution via https://github.com/angular/angular.io/issues/1919.

**Closed by chalin** 2016-11-29 18:06 UTC
